<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUM02L7699" name="Login and Update Profile Test" tests="1" failures="1" timestamp="1 Nov 2019 14:50:12 GMT" time="37.803" errors="0">
  <testcase name="feature" time="35.459" classname="runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at runner.TestRunner.feature(TestRunner.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]
	at steps.demo.verify_Save_As_Draft_button_is_visible(demo.java:56)
	at âœ½.Then Verify Save As Draft button is visible(features/DemoWeb.feature:27)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Login and Update Profile Test -->
